# Trading pairs
trading_pairs:
  - BTC/USDT
  - ETH/USDT
interval: 1m  # Data interval (e.g., 1 minute)
strategy: moving_average  # Default strategy


# Strategies
strategies:
  primary:
    type: combined
    consensus_threshold: 2
    strategies:
      - type: sma_crossover
        params:
          short_window: 50
          long_window: 200
      - type: stochastic
        params:
          k_period: 14
          d_period: 3
          overbought: 80
          oversold: 20

# Risk params
risk_params:
  max_position_size: 0.1  # 10% of total balance
  stop_loss_pct: 2.0      # 2% stop-loss
  take_profit_pct: 3.0    # 3% take-profit
  risk_per_trade: 1.0      # 1% risk per trade    


scheduler:
  interval: 5m  # Default strategy execution interval

database:
  path: "data/crypto_data.db"

monitoring:
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    email: "your-email@gmail.com"
    password: "your-app-password"
  health_checks:
    cpu: 80
    memory: 90


exchanges:
  - id: binance
    api_key: "your_binance_key"
    api_secret: "your_binance_secret"
    enabled: true
  - id: kraken
    api_key: "your_kraken_key"
    api_secret: "your_kraken_secret"
    enabled: false    