# config/config.yaml
---
# Core trading parameters
trading_pair: BTC/USDT  # Single pair for focus
interval: 5m            # Align with scheduler interval

# Exchange configuration (single active exchange)
exchange:
  id: binance
  api_key: "your_binance_key"
  api_secret: "your_binance_secret"
  enabled: true

# Primary strategy configuration
strategy:
  type: weighted
  params:
    buy_threshold: 0.65
  strategies:
    - type: moving_average
      params:
        short_window: 10
        long_window: 50
    - type: stochastic
      params:
        k_period: 14
        d_period: 3
        overbought: 80
        oversold: 20

# Risk management
risk_params:
  max_position_size: 0.1
  risk_per_trade: 0.01
  stop_loss_pct: 2.0
  take_profit_pct: 3.0
  max_daily_drawdown: 5.0
  consecutive_loss_limit: 3
  initial_balance: 10000.0

# System configuration
scheduler:
  interval: 5m  # Execution interval

database:
  path: "data/crypto_data.db"

monitoring:
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    email: "your-email@gmail.com"
    password: "your-app-password"
  health_checks:
    cpu: 80
    memory: 90
# Add a blank line below this comment →    